#!/usr/bin/env python3
"""Generate 400+ prefix command stubs — no slash command limit!"""

import os

STUBS = {
    "utility": [
        ("ping", "Check bot latency"),
        ("uptime", "Show bot uptime"),
        ("avatar", "Get a user's avatar"),
        ("userinfo", "Detailed user information"),
        ("serverinfo", "Server information"),
        ("roleinfo", "Role information"),
        ("channelinfo", "Channel information"),
        ("botinfo", "Bot statistics"),
        ("invite", "Bot invite link"),
        ("support", "Support server link"),
        ("vote", "Vote for the bot"),
        ("status", "Check bot status"),
        ("weather", "Weather lookup"),
        ("translate", "Translate text"),
        ("define", "Dictionary definition"),
        ("urban", "Urban Dictionary lookup"),
        ("crypto", "Cryptocurrency prices"),
        ("random", "Random number generator"),
        ("calc", "Calculator"),
        ("emoji", "Emoji info"),
        ("color", "Display a color"),
        ("hex", "Hex color info"),
        ("qrcode", "Generate QR code"),
        ("shorten", "Shorten a URL"),
        ("uuid", "Generate a UUID"),
        ("hash", "Hash text"),
        ("base64", "Base64 encode/decode"),
        ("json", "Format JSON"),
        ("timestamp", "Convert Unix timestamp"),
        ("countdown", "Countdown to date"),
        ("timer", "Set a timer"),
        ("remind", "Set a reminder"),
        ("todo", "Todo list"),
        ("note", "Take a note"),
        ("tag", "Create a tag"),
        ("tags", "List tags"),
        ("tagdelete", "Delete a tag"),
        ("tagedit", "Edit a tag"),
        ("poll", "Create a poll"),
        ("quickpoll", "Quick yes/no poll"),
        ("choose", "Choose between options"),
        ("rate", "Rate something"),
        ("settings", "User settings"),
        ("prefix", "Show bot prefix"),
        ("shard", "Shard info"),
        ("latency", "Bot latency"),
        ("node", "Node info"),
        ("animeinfo", "Anime info"),
        ("mangainfo", "Manga info"),
        ("malprofile", "MyAnimeList profile"),
        ("steamprofile", "Steam profile"),
        ("robloxprofile", "Roblox profile"),
        ("minecraftuuid", "Minecraft UUID"),
        ("fortnitestats", "Fortnite stats"),
        ("valorantstats", "Valorant stats"),
        ("serveravatar", "Server avatar"),
        ("banner", "User banner"),
        ("boosters", "Server boosters"),
        ("roles", "List your roles"),
        ("permissions", "Check permissions"),
        ("created", "Account creation date"),
        ("joined", "Join date"),
        ("members", "Member count"),
        ("emojis", "Server emoji list"),
        ("stickers", "Server sticker list"),
        ("webhooks", "Server webhooks"),
        ("auditlog", "Recent audit log"),
        ("invites", "Server invites"),
        ("vanity", "Vanity URL"),
        ("verification", "Verification level"),
        ("contentfilter", "Content filter level"),
        ("notifications", "Notification settings"),
        ("region", "Voice region"),
        ("afk", "AFK channel"),
        ("system", "System channel"),
        ("rules", "Rules channel"),
        ("updates", "Updates channel"),
        ("community", "Community info"),
    ],
    "economy": [
        ("balance", "Check balance"),
        ("daily", "Daily reward"),
        ("weekly", "Weekly reward"),
        ("work", "Work for money"),
        ("crime", "Commit a crime"),
        ("rob", "Rob a user"),
        ("give", "Give money"),
        ("shop", "View shop"),
        ("buy", "Buy an item"),
        ("sell", "Sell an item"),
        ("inventory", "View inventory"),
        ("ecoleaderboard", "Economy leaderboard"),
        ("gamble", "Gamble money"),
        ("slot", "Slot machine"),
        ("blackjack", "Blackjack"),
        ("deposit", "Deposit to bank"),
        ("withdraw", "Withdraw from bank"),
        ("bank", "Bank balance"),
        ("transfer", "Transfer money"),
        ("pay", "Pay a user"),
        ("beg", "Beg for money"),
        ("search", "Search for money"),
        ("hunt", "Hunt for money"),
        ("fish", "Fish for money"),
        ("mine", "Mine for money"),
        ("chop", "Chop wood for money"),
        ("dig", "Dig for money"),
        ("postmemes", "Post memes for money"),
        ("bake", "Bake for money"),
        ("sew", "Sew for money"),
        ("write", "Write for money"),
        ("paint", "Paint for money"),
        ("program", "Program for money"),
        ("sing", "Sing for money"),
        ("dance", "Dance for money"),
        ("stream", "Stream for money"),
        ("youtubemoney", "YouTube for money"),
        ("donate", "Donate to charity"),
        ("gift", "Gift an item"),
        ("trade", "Trade with user"),
        ("market", "Market prices"),
        ("stock", "Stock market"),
        ("invest", "Invest money"),
        ("robbery", "Plan a robbery"),
        ("heist", "Heist"),
        ("horse", "Horse betting"),
        ("lottery", "Lottery"),
        ("scratch", "Scratch card"),
    ],
    "games": [
        ("tictactoe", "Tic Tac Toe"),
        ("connect4", "Connect 4"),
        ("hangman", "Hangman"),
        ("trivia", "Trivia"),
        ("guess", "Guessing game"),
        ("typerace", "Type race"),
        ("anagram", "Anagram game"),
        ("battleship", "Battleship"),
        ("chess", "Chess move"),
        ("checkers", "Checkers"),
        ("poker", "Poker"),
        ("solitaire", "Solitaire"),
        ("sudoku", "Sudoku"),
        ("crossword", "Crossword"),
        ("wordsearch", "Word search"),
        ("scrabble", "Scrabble"),
        ("bingo", "Bingo"),
        ("memory", "Memory game"),
        ("maze", "Maze generator"),
        ("snake", "Snake game"),
        ("tetris", "Tetris"),
        ("pong", "Pong"),
        ("rpsls", "Rock Paper Scissors Lizard Spock"),
        ("dicepoker", "Dice poker"),
        ("liarsdice", "Liar's dice"),
        ("roulette", "Roulette"),
        ("craps", "Craps"),
        ("war", "War card game"),
        ("go", "Go game"),
        ("othello", "Othello/Reversi"),
        ("mastermind", "Mastermind"),
        ("wordle", "Wordle"),
        ("rpg", "RPG battle"),
        ("dungeon", "Dungeon crawler"),
        ("farm", "Farming game"),
        ("pet", "Virtual pet"),
        ("zoo", "Zoo tycoon"),
        ("city", "City builder"),
        ("clicker", "Clicker game"),
        ("idle", "Idle game"),
        ("tycoon", "Tycoon game"),
        ("simulator", "Simulator"),
        ("quiz", "Quiz game"),
        ("jeopardy", "Jeopardy"),
        ("wheel", "Wheel of fortune"),
        ("deal", "Deal or no deal"),
        ("millionaire", "Who wants to be a millionaire?"),
        ("familyfeud", "Family feud"),
        ("pyramid", "Pyramid game"),
        ("match", "Match game"),
        ("chain", "Word chain"),
        ("story", "Story builder"),
        ("horserace", "Horse race"),
        ("coinrace", "Coin race"),
    ],
    "info": [
        ("github", "GitHub lookup"),
        ("npmpackage", "NPM package"),
        ("pypipackage", "PyPI package"),
        ("ytinfo", "YouTube info"),
        ("twitchinfo", "Twitch stream check"),
        ("isup", "Is website up?"),
        ("domain", "Domain info"),
        ("ipinfo", "IP info"),
        ("whois", "Whois lookup"),
        ("dns", "DNS lookup"),
        ("port", "Port check"),
        ("headers", "HTTP headers"),
        ("sslcheck", "SSL check"),
        ("covid", "COVID stats"),
        ("news", "Latest news"),
        ("reddit", "Reddit info"),
        ("insta", "Instagram info"),
        ("tiktok", "TikTok info"),
        ("snapchat", "Snapchat info"),
        ("spotify", "Spotify track info"),
        ("soundcloud", "SoundCloud info"),
        ("bandcamp", "Bandcamp info"),
        ("applemusic", "Apple Music info"),
        ("deezer", "Deezer info"),
        ("wikipedia", "Wikipedia lookup"),
        ("dictionary", "Dictionary lookup"),
        ("thesaurus", "Thesaurus lookup"),
        ("currency", "Currency converter"),
        ("unitconverter", "Unit converter"),
        ("timezone", "Timezone converter"),
        ("calendar", "Calendar info"),
        ("holiday", "Holiday info"),
        ("moonphase", "Moon phase"),
        ("sunrise", "Sunrise/sunset"),
        ("tide", "Tide info"),
        ("earthquake", "Recent earthquakes"),
        ("aurora", "Aurora forecast"),
        ("isslocation", "ISS location"),
        ("spacex", "SpaceX launches"),
        ("nasa", "NASA APOD"),
    ],
    "admin": [
        ("setprefix", "Set prefix"),
        ("setwelcome", "Set welcome channel"),
        ("setleave", "Set leave channel"),
        ("welcomemsg", "Welcome message"),
        ("leavemsg", "Leave message"),
        ("modlog", "Set mod log"),
        ("autorole", "Set autorole"),
        ("muterole", "Set mute role"),
        ("reactionrole", "Reaction role"),
        ("ticket", "Ticket system"),
        ("ticketcategory", "Ticket category"),
        ("ticketrole", "Ticket support role"),
        ("logchannel", "Log channel"),
        ("joinlog", "Join log"),
        ("leavelog", "Leave log"),
        ("messagelog", "Message log"),
        ("voicelog", "Voice log"),
        ("banlog", "Ban log"),
        ("kicklog", "Kick log"),
        ("warnlog", "Warn log"),
        ("commandlog", "Command log"),
        ("suggestion", "Suggestion channel"),
        ("report", "Report channel"),
        ("appeal", "Appeal channel"),
        ("verify", "Verification system"),
        ("captcha", "Captcha verification"),
        ("gate", "Member gate"),
        ("antispam", "Anti-spam settings"),
        ("antilink", "Anti-link settings"),
        ("antiraid", "Anti-raid settings"),
        ("automod", "Auto-moderation"),
        ("backup", "Backup server"),
    ],
    "owner": [
        ("eval", "Evaluate Python"),
        ("shell", "Execute shell"),
        ("loadcog", "Load cog"),
        ("unloadcog", "Unload cog"),
        ("reloadcogs", "Reload all cogs"),
        ("shutdown", "Shutdown bot"),
        ("restartbot", "Restart bot"),
        ("broadcast", "Broadcast"),
        ("dmuser", "DM user"),
        ("listservers", "List servers"),
        ("leaveserver", "Leave a server"),
        ("blacklist", "Blacklist user"),
        ("unblacklist", "Unblacklist user"),
        ("whitelist", "Whitelist user"),
        ("maintenance", "Maintenance mode"),
        ("announce", "Global announcement"),
        ("updatebot", "Update bot"),
        ("gitpull", "Git pull"),
        ("gitcmd", "Git command"),
        ("viewlogs", "View bot logs"),
        ("debugmode", "Debug mode"),
        ("testcmd", "Test command"),
        ("checkperms", "Check permissions"),
        ("clearcache", "Clear cache"),
        ("resetdata", "Reset all data"),
    ],
    "roles": [
        ("role", "Toggle role"),
        ("roleadd", "Add role"),
        ("roleremove", "Remove role"),
        ("rolelist", "List roles"),
        ("rolecreate", "Create role"),
        ("roledelete", "Delete role"),
        ("rolecolor", "Change role color"),
        ("rolename", "Rename role"),
        ("rolehoist", "Toggle hoist"),
        ("rolemention", "Toggle mentionable"),
        ("roleperms", "Role permissions"),
        ("roleposition", "Role position"),
        ("roleicon", "Role icon"),
        ("roleid", "Role ID"),
        ("rolemembers", "Role members"),
        ("rolecount", "Role member count"),
        ("roleaddall", "Add role to all"),
        ("roleremoveall", "Remove role from all"),
        ("rolehumans", "Role humans only"),
        ("rolebots", "Role bots only"),
    ],
    "image": [
        ("blur", "Blur image"),
        ("pixelate", "Pixelate"),
        ("invert", "Invert colors"),
        ("grayscale", "Grayscale"),
        ("sepia", "Sepia filter"),
        ("resize", "Resize"),
        ("rotate", "Rotate"),
        ("flip", "Flip"),
        ("caption", "Add caption"),
        ("wanted", "Wanted poster"),
        ("triggered", "Triggered overlay"),
        ("jail", "Jail overlay"),
        ("gaypride", "Gay pride overlay"),
        ("rainbow", "Rainbow filter"),
        ("deepfry", "Deep fry"),
        ("magik", "Magik"),
        ("explosion", "Explosion effect"),
        ("glitch", "Glitch effect"),
        ("sketch", "Sketch filter"),
        ("oilpainting", "Oil painting"),
        ("watercolor", "Watercolor"),
        ("neon", "Neon effect"),
        ("imgascii", "ASCII art from image"),
        ("memegen", "Meme generator"),
        ("changemymind", "Change my mind"),
        ("distracted", "Distracted boyfriend"),
        ("drakememe", "Drake meme"),
        ("stonks", "Stonks meme"),
        ("disastergirl", "Disaster girl"),
        ("panicbutton", "Panic button"),
    ],
    "leveling": [
        ("rank", "Your rank"),
        ("lvleaderboard", "Level leaderboard"),
        ("setlevel", "Set level"),
        ("setxp", "Set XP"),
        ("levelrewards", "Level rewards"),
        ("addreward", "Add reward"),
        ("remreward", "Remove reward"),
        ("xprate", "XP rate"),
        ("xpboost", "XP boost"),
        ("xpblacklist", "XP blacklist channel"),
        ("xpwhitelist", "XP whitelist channel"),
        ("levelannounce", "Level up announce"),
        ("rankcard", "Rank card"),
        ("cardcolor", "Rank card color"),
        ("cardbg", "Rank card background"),
        ("resetxp", "Reset all XP"),
        ("resetlevel", "Reset level"),
        ("setexactxp", "Set exact XP"),
        ("addxp", "Add XP to user"),
        ("removexp", "Remove XP from user"),
    ],
    "misc": [
        ("makepoll", "Create poll"),
        ("settimer", "Set timer"),
        ("setremind", "Set reminder"),
        ("todolist", "Todo list"),
        ("makenote", "Take note"),
        ("createtag", "Create tag"),
        ("listtags", "List tags"),
        ("deletetag", "Delete tag"),
        ("edittag", "Edit tag"),
        ("taginfo", "Tag info"),
        ("tagtransfer", "Transfer tag"),
        ("tagclaim", "Claim tag"),
        ("counter", "Counter"),
        ("count", "Count up/down"),
        ("savemsg", "Save message"),
        ("viewsaved", "View saved messages"),
        ("unsave", "Unsave message"),
        ("pinmsg", "Pin message"),
        ("unpinmsg", "Unpin message"),
        ("listpins", "List pins"),
        ("snipe", "Snipe deleted message"),
        ("editsnipe", "Snipe edited message"),
        ("addreaction", "Add reaction"),
        ("emojilist", "Server emojis"),
        ("stickerlist", "Server stickers"),
        ("soundboard", "Soundboard"),
        ("playlist", "Playlist"),
        ("radio", "Radio station"),
        ("voiceinfo", "Voice channel info"),
        ("vcmove", "Move voice members"),
        ("vcname", "Rename voice channel"),
        ("vclimit", "Set voice user limit"),
        ("vcbitrate", "Set voice bitrate"),
        ("vcregion", "Set voice region"),
        ("weatherinfo", "Weather info detail"),
        ("defineword", "Define word detail"),
        ("synonym", "Thesaurus"),
        ("translatetext", "Translate text detail"),
    ],
}


def generate_stub(name, desc):
    safe = name.replace("-", "_").replace(" ", "_")
    if safe[0].isdigit():
        safe = f"_{safe}"
    
    reserved = {
        "eval", "exec", "hash", "import", "global", "lambda", "class", 
        "def", "pass", "return", "yield", "raise", "try", "except", 
        "finally", "with", "as"
    }
    if safe in reserved:
        safe = f"_{safe}"

    return f'''    @commands.command(name="{name}", help="{desc}")
    async def {safe}(self, ctx):
        """{desc}."""
        await ctx.send(embed=make_embed(title="{desc}", description="Command stub — implement me!", color=0x5865F2))
'''


def main():
    os.makedirs("cogs", exist_ok=True)
    total = 0
    for cog, cmds in STUBS.items():
        path = f"cogs/{cog}_cog.py"

        with open(path, "w", encoding="utf-8") as f:
            f.write(f'''import discord
from discord.ext import commands
from utils.embed_builder import make_embed


class {cog.title()}Cog(commands.Cog, name="{cog}"):
    """{cog.title()} commands"""

    def __init__(self, bot):
        self.bot = bot

''')
            for name, desc in cmds:
                f.write(generate_stub(name, desc))
                f.write("\n")

            f.write(f'''
async def setup(bot):
    await bot.add_cog({cog.title()}Cog(bot))
''')
        print(f"[+] {path} ({len(cmds)} commands)")
        total += len(cmds)

    print(f"\n[✓] Generated {total} prefix command stubs across {len(STUBS)} cogs!")


if __name__ == "__main__":
    main()